# Generated by Django 3.2 on 2021-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('notcompleted', 'notcompleted')], default='notcompleted', max_length=12)),
                ('user', models.CharField(max_length=12)),
            ],
        ),
    ]
