# Generated by Django 3.2 on 2021-05-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='taskname',
        ),
        migrations.AddField(
            model_name='todo',
            name='task_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
